[[servers]]
host = "192.168.1.5"
port = 389
use_ssl = false
start_tls = false
ssl_skip_verify = false
bind_dn = "uid=anonymous,dc=AB"
bind_password = 'passwd'
search_filter = "(mail=%s)"
search_base_dns = ["dc=AB"]
[servers.attributes]
name = "givenName"
surname = "sn"
username = "cn"
member_of = "memberOf"
email =  "email"
[[servers.group_mappings]]
group_dn = "cn=admins,dc=grafana,dc=org"
org_role = "Admin"
[[servers.group_mappings]]
group_dn = "cn=users,dc=grafana,dc=org"
org_role = "Editor"
[[servers.group_mappings]]
group_dn = "*"
org_role = "Viewer"
